#############################################################################
# Makefile for building: ImplicitMuscles
# Generated by qmake (3.0) (Qt 5.5.0)
# Project:  implicitMuscles.pro
# Template: app
# Command: /usr/bin/qmake-qt5 -spec linux-g++ CONFIG+=debug -o Makefile implicitMuscles.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -std=c++0x -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -Iinclude -Iui -I../glm -Ishaders -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtOpenGL -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtCore -Imoc -Iui -I/usr/lib64/qt5/mkspecs/linux-g++
QMAKE         = /usr/bin/qmake-qt5
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = ImplicitMuscles1.0.0
DISTDIR = /home/kedge/Documents/implicitMuscles/obj/ImplicitMuscles1.0.0
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS) -lGLU -lGLEW -lQt5OpenGL -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = 

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = src/main.cpp \
		src/MainWindow.cpp \
		src/GLWindow.cpp \
		src/Camera.cpp \
		src/TrackballCamera.cpp \
		src/Shader.cpp \
		src/Mesh.cpp \
		src/Scene.cpp \
		src/Buffer.cpp \
		src/marchingcube.cpp moc/moc_MainWindow.cpp \
		moc/moc_GLWindow.cpp
OBJECTS       = obj/main.o \
		obj/MainWindow.o \
		obj/GLWindow.o \
		obj/Camera.o \
		obj/TrackballCamera.o \
		obj/Shader.o \
		obj/Mesh.o \
		obj/Scene.o \
		obj/Buffer.o \
		obj/marchingcube.o \
		obj/moc_MainWindow.o \
		obj/moc_GLWindow.o
DIST          = shaders/implicitmuscle.glsl \
		/usr/lib64/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib64/qt5/mkspecs/common/unix.conf \
		/usr/lib64/qt5/mkspecs/common/linux.conf \
		/usr/lib64/qt5/mkspecs/common/sanitize.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt5/mkspecs/common/g++-base.conf \
		/usr/lib64/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt5/mkspecs/qconfig.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib64/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt5/mkspecs/features/qt_config.prf \
		/usr/lib64/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib64/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib64/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt5/mkspecs/features/default_pre.prf \
		/usr/lib64/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib64/qt5/mkspecs/features/default_post.prf \
		/usr/lib64/qt5/mkspecs/features/c++11.prf \
		/usr/lib64/qt5/mkspecs/features/warn_on.prf \
		/usr/lib64/qt5/mkspecs/features/qt.prf \
		/usr/lib64/qt5/mkspecs/features/resources.prf \
		/usr/lib64/qt5/mkspecs/features/moc.prf \
		/usr/lib64/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib64/qt5/mkspecs/features/uic.prf \
		/usr/lib64/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib64/qt5/mkspecs/features/exceptions.prf \
		/usr/lib64/qt5/mkspecs/features/yacc.prf \
		/usr/lib64/qt5/mkspecs/features/lex.prf \
		implicitMuscles.pro include/MainWindow.h \
		include/GLWindow.h \
		include/Camera.h \
		include/TrackballCamera.h \
		include/Shader.h \
		include/Mesh.h \
		include/Scene.h \
		include/Buffer.h \
		include/marchingcube.h src/main.cpp \
		src/MainWindow.cpp \
		src/GLWindow.cpp \
		src/Camera.cpp \
		src/TrackballCamera.cpp \
		src/Shader.cpp \
		src/Mesh.cpp \
		src/Scene.cpp \
		src/Buffer.cpp \
		src/marchingcube.cpp
QMAKE_TARGET  = ImplicitMuscles
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = ImplicitMuscles


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET): ui/ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: implicitMuscles.pro /usr/lib64/qt5/mkspecs/linux-g++/qmake.conf /usr/lib64/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib64/qt5/mkspecs/common/unix.conf \
		/usr/lib64/qt5/mkspecs/common/linux.conf \
		/usr/lib64/qt5/mkspecs/common/sanitize.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt5/mkspecs/common/g++-base.conf \
		/usr/lib64/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt5/mkspecs/qconfig.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib64/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt5/mkspecs/features/qt_config.prf \
		/usr/lib64/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib64/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib64/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt5/mkspecs/features/default_pre.prf \
		/usr/lib64/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib64/qt5/mkspecs/features/default_post.prf \
		/usr/lib64/qt5/mkspecs/features/c++11.prf \
		/usr/lib64/qt5/mkspecs/features/warn_on.prf \
		/usr/lib64/qt5/mkspecs/features/qt.prf \
		/usr/lib64/qt5/mkspecs/features/resources.prf \
		/usr/lib64/qt5/mkspecs/features/moc.prf \
		/usr/lib64/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib64/qt5/mkspecs/features/uic.prf \
		/usr/lib64/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib64/qt5/mkspecs/features/exceptions.prf \
		/usr/lib64/qt5/mkspecs/features/yacc.prf \
		/usr/lib64/qt5/mkspecs/features/lex.prf \
		implicitMuscles.pro \
		/usr/lib64/libQt5OpenGL.prl \
		/usr/lib64/libQt5Widgets.prl \
		/usr/lib64/libQt5Gui.prl \
		/usr/lib64/libQt5Core.prl
	$(QMAKE) -spec linux-g++ CONFIG+=debug -o Makefile implicitMuscles.pro
/usr/lib64/qt5/mkspecs/features/spec_pre.prf:
/usr/lib64/qt5/mkspecs/common/unix.conf:
/usr/lib64/qt5/mkspecs/common/linux.conf:
/usr/lib64/qt5/mkspecs/common/sanitize.conf:
/usr/lib64/qt5/mkspecs/common/gcc-base.conf:
/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib64/qt5/mkspecs/common/g++-base.conf:
/usr/lib64/qt5/mkspecs/common/g++-unix.conf:
/usr/lib64/qt5/mkspecs/qconfig.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib64/qt5/mkspecs/features/qt_functions.prf:
/usr/lib64/qt5/mkspecs/features/qt_config.prf:
/usr/lib64/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib64/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib64/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib64/qt5/mkspecs/features/default_pre.prf:
/usr/lib64/qt5/mkspecs/features/resolve_config.prf:
/usr/lib64/qt5/mkspecs/features/default_post.prf:
/usr/lib64/qt5/mkspecs/features/c++11.prf:
/usr/lib64/qt5/mkspecs/features/warn_on.prf:
/usr/lib64/qt5/mkspecs/features/qt.prf:
/usr/lib64/qt5/mkspecs/features/resources.prf:
/usr/lib64/qt5/mkspecs/features/moc.prf:
/usr/lib64/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib64/qt5/mkspecs/features/uic.prf:
/usr/lib64/qt5/mkspecs/features/unix/thread.prf:
/usr/lib64/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib64/qt5/mkspecs/features/exceptions.prf:
/usr/lib64/qt5/mkspecs/features/yacc.prf:
/usr/lib64/qt5/mkspecs/features/lex.prf:
implicitMuscles.pro:
/usr/lib64/libQt5OpenGL.prl:
/usr/lib64/libQt5Widgets.prl:
/usr/lib64/libQt5Gui.prl:
/usr/lib64/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -spec linux-g++ CONFIG+=debug -o Makefile implicitMuscles.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents include/MainWindow.h include/GLWindow.h include/Camera.h include/TrackballCamera.h include/Shader.h include/Mesh.h include/Scene.h include/Buffer.h include/marchingcube.h $(DISTDIR)/
	$(COPY_FILE) --parents src/main.cpp src/MainWindow.cpp src/GLWindow.cpp src/Camera.cpp src/TrackballCamera.cpp src/Shader.cpp src/Mesh.cpp src/Scene.cpp src/Buffer.cpp src/marchingcube.cpp $(DISTDIR)/
	$(COPY_FILE) --parents ui/mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc/moc_MainWindow.cpp moc/moc_GLWindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc/moc_MainWindow.cpp moc/moc_GLWindow.cpp
moc/moc_MainWindow.cpp: include/GLWindow.h \
		include/Shader.h \
		include/TrackballCamera.h \
		include/Camera.h \
		../glm/glm.hpp \
		../glm/detail/_fixes.hpp \
		../glm/fwd.hpp \
		../glm/detail/type_int.hpp \
		../glm/detail/setup.hpp \
		../glm/simd/platform.h \
		../glm/detail/type_float.hpp \
		../glm/detail/type_vec.hpp \
		../glm/detail/precision.hpp \
		../glm/detail/type_mat.hpp \
		../glm/vec2.hpp \
		../glm/detail/type_vec2.hpp \
		../glm/detail/_swizzle.hpp \
		../glm/detail/_swizzle_func.hpp \
		../glm/detail/type_vec2.inl \
		../glm/vec3.hpp \
		../glm/detail/type_vec3.hpp \
		../glm/detail/type_vec3.inl \
		../glm/vec4.hpp \
		../glm/detail/type_vec4.hpp \
		../glm/detail/type_vec4.inl \
		../glm/detail/type_vec4_simd.inl \
		../glm/mat2x2.hpp \
		../glm/detail/type_mat2x2.hpp \
		../glm/detail/type_mat2x2.inl \
		../glm/detail/func_matrix.hpp \
		../glm/mat2x3.hpp \
		../glm/detail/type_mat2x3.hpp \
		../glm/detail/type_mat2x3.inl \
		../glm/mat2x4.hpp \
		../glm/detail/type_mat2x4.hpp \
		../glm/detail/type_mat2x4.inl \
		../glm/mat3x2.hpp \
		../glm/detail/type_mat3x2.hpp \
		../glm/detail/type_mat3x2.inl \
		../glm/mat3x3.hpp \
		../glm/detail/type_mat3x3.hpp \
		../glm/detail/type_mat3x3.inl \
		../glm/mat3x4.hpp \
		../glm/detail/type_mat3x4.hpp \
		../glm/detail/type_mat3x4.inl \
		../glm/mat4x2.hpp \
		../glm/detail/type_mat4x2.hpp \
		../glm/detail/type_mat4x2.inl \
		../glm/mat4x3.hpp \
		../glm/detail/type_mat4x3.hpp \
		../glm/detail/type_mat4x3.inl \
		../glm/mat4x4.hpp \
		../glm/detail/type_mat4x4.hpp \
		../glm/detail/type_mat4x4.inl \
		../glm/detail/type_mat4x4_simd.inl \
		../glm/detail/func_matrix.inl \
		../glm/geometric.hpp \
		../glm/detail/func_geometric.hpp \
		../glm/detail/func_geometric.inl \
		../glm/detail/func_exponential.hpp \
		../glm/detail/type_vec1.hpp \
		../glm/detail/type_vec1.inl \
		../glm/detail/func_exponential.inl \
		../glm/detail/func_vector_relational.hpp \
		../glm/detail/func_vector_relational.inl \
		../glm/detail/func_vector_relational_simd.inl \
		../glm/detail/_vectorize.hpp \
		../glm/detail/func_exponential_simd.inl \
		../glm/simd/exponential.h \
		../glm/detail/func_common.hpp \
		../glm/detail/func_common.inl \
		../glm/detail/func_common_simd.inl \
		../glm/simd/common.h \
		../glm/detail/func_geometric_simd.inl \
		../glm/simd/geometric.h \
		../glm/detail/func_matrix_simd.inl \
		../glm/simd/matrix.h \
		../glm/trigonometric.hpp \
		../glm/detail/func_trigonometric.hpp \
		../glm/detail/func_trigonometric.inl \
		../glm/detail/func_trigonometric_simd.inl \
		../glm/exponential.hpp \
		../glm/common.hpp \
		../glm/packing.hpp \
		../glm/detail/func_packing.hpp \
		../glm/detail/func_packing.inl \
		../glm/detail/type_half.hpp \
		../glm/detail/type_half.inl \
		../glm/detail/func_packing_simd.inl \
		../glm/matrix.hpp \
		../glm/vector_relational.hpp \
		../glm/integer.hpp \
		../glm/detail/func_integer.hpp \
		../glm/detail/func_integer.inl \
		../glm/detail/func_integer_simd.inl \
		../glm/simd/integer.h \
		../glm/gtc/matrix_transform.hpp \
		../glm/gtc/constants.hpp \
		../glm/gtc/constants.inl \
		../glm/gtc/matrix_transform.inl \
		../glm/gtx/string_cast.hpp \
		../glm/gtc/type_precision.hpp \
		../glm/gtc/quaternion.hpp \
		../glm/gtc/quaternion.inl \
		../glm/gtc/quaternion_simd.inl \
		../glm/gtc/vec1.hpp \
		../glm/gtc/vec1.inl \
		../glm/gtc/type_precision.inl \
		../glm/gtx/dual_quaternion.hpp \
		../glm/gtx/dual_quaternion.inl \
		../glm/gtx/string_cast.inl \
		include/Mesh.h \
		../glm/gtc/type_ptr.hpp \
		../glm/gtc/type_ptr.inl \
		../glm/ext.hpp \
		../glm/gtc/bitfield.hpp \
		../glm/gtc/bitfield.inl \
		../glm/gtc/color_space.hpp \
		../glm/gtc/color_space.inl \
		../glm/gtc/epsilon.hpp \
		../glm/gtc/epsilon.inl \
		../glm/gtc/functions.hpp \
		../glm/gtc/functions.inl \
		../glm/gtc/integer.hpp \
		../glm/gtc/integer.inl \
		../glm/gtc/matrix_access.hpp \
		../glm/gtc/matrix_access.inl \
		../glm/gtc/matrix_integer.hpp \
		../glm/gtc/matrix_inverse.hpp \
		../glm/gtc/matrix_inverse.inl \
		../glm/gtc/noise.hpp \
		../glm/detail/_noise.hpp \
		../glm/gtc/noise.inl \
		../glm/gtc/packing.hpp \
		../glm/gtc/packing.inl \
		../glm/gtc/random.hpp \
		../glm/gtc/random.inl \
		../glm/gtc/reciprocal.hpp \
		../glm/gtc/reciprocal.inl \
		../glm/gtc/round.hpp \
		../glm/gtc/round.inl \
		../glm/gtc/ulp.hpp \
		../glm/gtc/ulp.inl \
		../glm/gtc/type_aligned.hpp \
		../glm/gtx/associated_min_max.hpp \
		../glm/gtx/associated_min_max.inl \
		../glm/gtx/bit.hpp \
		../glm/gtx/bit.inl \
		../glm/gtx/closest_point.hpp \
		../glm/gtx/closest_point.inl \
		../glm/gtx/color_space.hpp \
		../glm/gtx/color_space_YCoCg.hpp \
		../glm/gtx/color_space_YCoCg.inl \
		../glm/gtx/compatibility.hpp \
		../glm/gtx/compatibility.inl \
		../glm/gtx/component_wise.hpp \
		../glm/gtx/component_wise.inl \
		../glm/gtx/euler_angles.hpp \
		../glm/gtx/euler_angles.inl \
		../glm/gtx/extend.hpp \
		../glm/gtx/extend.inl \
		../glm/gtx/extended_min_max.hpp \
		../glm/gtx/extended_min_max.inl \
		../glm/gtx/fast_exponential.hpp \
		../glm/gtx/fast_exponential.inl \
		../glm/gtx/fast_square_root.hpp \
		../glm/gtx/fast_square_root.inl \
		../glm/gtx/fast_trigonometry.hpp \
		../glm/gtx/fast_trigonometry.inl \
		../glm/gtx/gradient_paint.hpp \
		../glm/gtx/optimum_pow.hpp \
		../glm/gtx/optimum_pow.inl \
		../glm/gtx/gradient_paint.inl \
		../glm/gtx/handed_coordinate_space.hpp \
		../glm/gtx/handed_coordinate_space.inl \
		../glm/gtx/integer.hpp \
		../glm/gtx/intersect.hpp \
		../glm/gtx/vector_query.hpp \
		../glm/gtx/vector_query.inl \
		../glm/gtx/intersect.inl \
		../glm/gtx/log_base.hpp \
		../glm/gtx/log_base.inl \
		../glm/gtx/matrix_cross_product.hpp \
		../glm/gtx/matrix_cross_product.inl \
		../glm/gtx/matrix_interpolation.hpp \
		../glm/gtx/matrix_interpolation.inl \
		../glm/gtx/matrix_major_storage.hpp \
		../glm/gtx/matrix_major_storage.inl \
		../glm/gtx/matrix_operation.hpp \
		../glm/gtx/matrix_operation.inl \
		../glm/gtx/matrix_query.hpp \
		../glm/gtx/matrix_query.inl \
		../glm/gtx/mixed_product.hpp \
		../glm/gtx/mixed_product.inl \
		../glm/gtx/norm.hpp \
		../glm/gtx/quaternion.hpp \
		../glm/gtx/norm.inl \
		../glm/gtx/normal.hpp \
		../glm/gtx/normal.inl \
		../glm/gtx/normalize_dot.hpp \
		../glm/gtx/normalize_dot.inl \
		../glm/gtx/number_precision.hpp \
		../glm/gtx/number_precision.inl \
		../glm/gtx/orthonormalize.hpp \
		../glm/gtx/orthonormalize.inl \
		../glm/gtx/perpendicular.hpp \
		../glm/gtx/projection.hpp \
		../glm/gtx/projection.inl \
		../glm/gtx/perpendicular.inl \
		../glm/gtx/polar_coordinates.hpp \
		../glm/gtx/polar_coordinates.inl \
		../glm/gtx/raw_data.hpp \
		../glm/gtx/raw_data.inl \
		../glm/gtx/rotate_vector.hpp \
		../glm/gtx/transform.hpp \
		../glm/gtx/transform.inl \
		../glm/gtx/rotate_vector.inl \
		../glm/gtx/spline.hpp \
		../glm/gtx/spline.inl \
		../glm/gtx/std_based_type.hpp \
		../glm/gtx/std_based_type.inl \
		../glm/gtx/transform2.hpp \
		../glm/gtx/transform2.inl \
		../glm/gtx/vector_angle.hpp \
		../glm/gtx/vector_angle.inl \
		../glm/gtx/wrap.hpp \
		../glm/gtx/wrap.inl \
		../glm/gtx/scalar_multiplication.hpp \
		../glm/gtx/range.hpp \
		include/Buffer.h \
		include/marchingcube.h \
		include/MainWindow.h
	/usr/lib64/qt5/bin/moc $(DEFINES) -I/usr/lib64/qt5/mkspecs/linux-g++ -I/home/kedge/Documents/implicitMuscles -I/home/kedge/Documents/implicitMuscles/include -I/home/kedge/Documents/implicitMuscles/ui -I/home/kedge/Documents/glm -I/home/kedge/Documents/implicitMuscles/shaders -I/usr/include/qt5 -I/usr/include/qt5/QtOpenGL -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/include/c++/5.1.1 -I/usr/include/c++/5.1.1/x86_64-redhat-linux -I/usr/include/c++/5.1.1/backward -I/usr/lib/gcc/x86_64-redhat-linux/5.1.1/include -I/usr/local/include -I/usr/include include/MainWindow.h -o moc/moc_MainWindow.cpp

moc/moc_GLWindow.cpp: include/Shader.h \
		include/TrackballCamera.h \
		include/Camera.h \
		../glm/glm.hpp \
		../glm/detail/_fixes.hpp \
		../glm/fwd.hpp \
		../glm/detail/type_int.hpp \
		../glm/detail/setup.hpp \
		../glm/simd/platform.h \
		../glm/detail/type_float.hpp \
		../glm/detail/type_vec.hpp \
		../glm/detail/precision.hpp \
		../glm/detail/type_mat.hpp \
		../glm/vec2.hpp \
		../glm/detail/type_vec2.hpp \
		../glm/detail/_swizzle.hpp \
		../glm/detail/_swizzle_func.hpp \
		../glm/detail/type_vec2.inl \
		../glm/vec3.hpp \
		../glm/detail/type_vec3.hpp \
		../glm/detail/type_vec3.inl \
		../glm/vec4.hpp \
		../glm/detail/type_vec4.hpp \
		../glm/detail/type_vec4.inl \
		../glm/detail/type_vec4_simd.inl \
		../glm/mat2x2.hpp \
		../glm/detail/type_mat2x2.hpp \
		../glm/detail/type_mat2x2.inl \
		../glm/detail/func_matrix.hpp \
		../glm/mat2x3.hpp \
		../glm/detail/type_mat2x3.hpp \
		../glm/detail/type_mat2x3.inl \
		../glm/mat2x4.hpp \
		../glm/detail/type_mat2x4.hpp \
		../glm/detail/type_mat2x4.inl \
		../glm/mat3x2.hpp \
		../glm/detail/type_mat3x2.hpp \
		../glm/detail/type_mat3x2.inl \
		../glm/mat3x3.hpp \
		../glm/detail/type_mat3x3.hpp \
		../glm/detail/type_mat3x3.inl \
		../glm/mat3x4.hpp \
		../glm/detail/type_mat3x4.hpp \
		../glm/detail/type_mat3x4.inl \
		../glm/mat4x2.hpp \
		../glm/detail/type_mat4x2.hpp \
		../glm/detail/type_mat4x2.inl \
		../glm/mat4x3.hpp \
		../glm/detail/type_mat4x3.hpp \
		../glm/detail/type_mat4x3.inl \
		../glm/mat4x4.hpp \
		../glm/detail/type_mat4x4.hpp \
		../glm/detail/type_mat4x4.inl \
		../glm/detail/type_mat4x4_simd.inl \
		../glm/detail/func_matrix.inl \
		../glm/geometric.hpp \
		../glm/detail/func_geometric.hpp \
		../glm/detail/func_geometric.inl \
		../glm/detail/func_exponential.hpp \
		../glm/detail/type_vec1.hpp \
		../glm/detail/type_vec1.inl \
		../glm/detail/func_exponential.inl \
		../glm/detail/func_vector_relational.hpp \
		../glm/detail/func_vector_relational.inl \
		../glm/detail/func_vector_relational_simd.inl \
		../glm/detail/_vectorize.hpp \
		../glm/detail/func_exponential_simd.inl \
		../glm/simd/exponential.h \
		../glm/detail/func_common.hpp \
		../glm/detail/func_common.inl \
		../glm/detail/func_common_simd.inl \
		../glm/simd/common.h \
		../glm/detail/func_geometric_simd.inl \
		../glm/simd/geometric.h \
		../glm/detail/func_matrix_simd.inl \
		../glm/simd/matrix.h \
		../glm/trigonometric.hpp \
		../glm/detail/func_trigonometric.hpp \
		../glm/detail/func_trigonometric.inl \
		../glm/detail/func_trigonometric_simd.inl \
		../glm/exponential.hpp \
		../glm/common.hpp \
		../glm/packing.hpp \
		../glm/detail/func_packing.hpp \
		../glm/detail/func_packing.inl \
		../glm/detail/type_half.hpp \
		../glm/detail/type_half.inl \
		../glm/detail/func_packing_simd.inl \
		../glm/matrix.hpp \
		../glm/vector_relational.hpp \
		../glm/integer.hpp \
		../glm/detail/func_integer.hpp \
		../glm/detail/func_integer.inl \
		../glm/detail/func_integer_simd.inl \
		../glm/simd/integer.h \
		../glm/gtc/matrix_transform.hpp \
		../glm/gtc/constants.hpp \
		../glm/gtc/constants.inl \
		../glm/gtc/matrix_transform.inl \
		../glm/gtx/string_cast.hpp \
		../glm/gtc/type_precision.hpp \
		../glm/gtc/quaternion.hpp \
		../glm/gtc/quaternion.inl \
		../glm/gtc/quaternion_simd.inl \
		../glm/gtc/vec1.hpp \
		../glm/gtc/vec1.inl \
		../glm/gtc/type_precision.inl \
		../glm/gtx/dual_quaternion.hpp \
		../glm/gtx/dual_quaternion.inl \
		../glm/gtx/string_cast.inl \
		include/Mesh.h \
		../glm/gtc/type_ptr.hpp \
		../glm/gtc/type_ptr.inl \
		../glm/ext.hpp \
		../glm/gtc/bitfield.hpp \
		../glm/gtc/bitfield.inl \
		../glm/gtc/color_space.hpp \
		../glm/gtc/color_space.inl \
		../glm/gtc/epsilon.hpp \
		../glm/gtc/epsilon.inl \
		../glm/gtc/functions.hpp \
		../glm/gtc/functions.inl \
		../glm/gtc/integer.hpp \
		../glm/gtc/integer.inl \
		../glm/gtc/matrix_access.hpp \
		../glm/gtc/matrix_access.inl \
		../glm/gtc/matrix_integer.hpp \
		../glm/gtc/matrix_inverse.hpp \
		../glm/gtc/matrix_inverse.inl \
		../glm/gtc/noise.hpp \
		../glm/detail/_noise.hpp \
		../glm/gtc/noise.inl \
		../glm/gtc/packing.hpp \
		../glm/gtc/packing.inl \
		../glm/gtc/random.hpp \
		../glm/gtc/random.inl \
		../glm/gtc/reciprocal.hpp \
		../glm/gtc/reciprocal.inl \
		../glm/gtc/round.hpp \
		../glm/gtc/round.inl \
		../glm/gtc/ulp.hpp \
		../glm/gtc/ulp.inl \
		../glm/gtc/type_aligned.hpp \
		../glm/gtx/associated_min_max.hpp \
		../glm/gtx/associated_min_max.inl \
		../glm/gtx/bit.hpp \
		../glm/gtx/bit.inl \
		../glm/gtx/closest_point.hpp \
		../glm/gtx/closest_point.inl \
		../glm/gtx/color_space.hpp \
		../glm/gtx/color_space_YCoCg.hpp \
		../glm/gtx/color_space_YCoCg.inl \
		../glm/gtx/compatibility.hpp \
		../glm/gtx/compatibility.inl \
		../glm/gtx/component_wise.hpp \
		../glm/gtx/component_wise.inl \
		../glm/gtx/euler_angles.hpp \
		../glm/gtx/euler_angles.inl \
		../glm/gtx/extend.hpp \
		../glm/gtx/extend.inl \
		../glm/gtx/extended_min_max.hpp \
		../glm/gtx/extended_min_max.inl \
		../glm/gtx/fast_exponential.hpp \
		../glm/gtx/fast_exponential.inl \
		../glm/gtx/fast_square_root.hpp \
		../glm/gtx/fast_square_root.inl \
		../glm/gtx/fast_trigonometry.hpp \
		../glm/gtx/fast_trigonometry.inl \
		../glm/gtx/gradient_paint.hpp \
		../glm/gtx/optimum_pow.hpp \
		../glm/gtx/optimum_pow.inl \
		../glm/gtx/gradient_paint.inl \
		../glm/gtx/handed_coordinate_space.hpp \
		../glm/gtx/handed_coordinate_space.inl \
		../glm/gtx/integer.hpp \
		../glm/gtx/intersect.hpp \
		../glm/gtx/vector_query.hpp \
		../glm/gtx/vector_query.inl \
		../glm/gtx/intersect.inl \
		../glm/gtx/log_base.hpp \
		../glm/gtx/log_base.inl \
		../glm/gtx/matrix_cross_product.hpp \
		../glm/gtx/matrix_cross_product.inl \
		../glm/gtx/matrix_interpolation.hpp \
		../glm/gtx/matrix_interpolation.inl \
		../glm/gtx/matrix_major_storage.hpp \
		../glm/gtx/matrix_major_storage.inl \
		../glm/gtx/matrix_operation.hpp \
		../glm/gtx/matrix_operation.inl \
		../glm/gtx/matrix_query.hpp \
		../glm/gtx/matrix_query.inl \
		../glm/gtx/mixed_product.hpp \
		../glm/gtx/mixed_product.inl \
		../glm/gtx/norm.hpp \
		../glm/gtx/quaternion.hpp \
		../glm/gtx/norm.inl \
		../glm/gtx/normal.hpp \
		../glm/gtx/normal.inl \
		../glm/gtx/normalize_dot.hpp \
		../glm/gtx/normalize_dot.inl \
		../glm/gtx/number_precision.hpp \
		../glm/gtx/number_precision.inl \
		../glm/gtx/orthonormalize.hpp \
		../glm/gtx/orthonormalize.inl \
		../glm/gtx/perpendicular.hpp \
		../glm/gtx/projection.hpp \
		../glm/gtx/projection.inl \
		../glm/gtx/perpendicular.inl \
		../glm/gtx/polar_coordinates.hpp \
		../glm/gtx/polar_coordinates.inl \
		../glm/gtx/raw_data.hpp \
		../glm/gtx/raw_data.inl \
		../glm/gtx/rotate_vector.hpp \
		../glm/gtx/transform.hpp \
		../glm/gtx/transform.inl \
		../glm/gtx/rotate_vector.inl \
		../glm/gtx/spline.hpp \
		../glm/gtx/spline.inl \
		../glm/gtx/std_based_type.hpp \
		../glm/gtx/std_based_type.inl \
		../glm/gtx/transform2.hpp \
		../glm/gtx/transform2.inl \
		../glm/gtx/vector_angle.hpp \
		../glm/gtx/vector_angle.inl \
		../glm/gtx/wrap.hpp \
		../glm/gtx/wrap.inl \
		../glm/gtx/scalar_multiplication.hpp \
		../glm/gtx/range.hpp \
		include/Buffer.h \
		include/GLWindow.h
	/usr/lib64/qt5/bin/moc $(DEFINES) -I/usr/lib64/qt5/mkspecs/linux-g++ -I/home/kedge/Documents/implicitMuscles -I/home/kedge/Documents/implicitMuscles/include -I/home/kedge/Documents/implicitMuscles/ui -I/home/kedge/Documents/glm -I/home/kedge/Documents/implicitMuscles/shaders -I/usr/include/qt5 -I/usr/include/qt5/QtOpenGL -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/include/c++/5.1.1 -I/usr/include/c++/5.1.1/x86_64-redhat-linux -I/usr/include/c++/5.1.1/backward -I/usr/lib/gcc/x86_64-redhat-linux/5.1.1/include -I/usr/local/include -I/usr/include include/GLWindow.h -o moc/moc_GLWindow.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui/ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui/ui_mainwindow.h
ui/ui_mainwindow.h: ui/mainwindow.ui
	/usr/lib64/qt5/bin/uic ui/mainwindow.ui -o ui/ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

obj/main.o: src/main.cpp include/MainWindow.h \
		include/GLWindow.h \
		include/Shader.h \
		include/TrackballCamera.h \
		include/Camera.h \
		../glm/glm.hpp \
		../glm/detail/_fixes.hpp \
		../glm/fwd.hpp \
		../glm/detail/type_int.hpp \
		../glm/detail/setup.hpp \
		../glm/simd/platform.h \
		../glm/detail/type_float.hpp \
		../glm/detail/type_vec.hpp \
		../glm/detail/precision.hpp \
		../glm/detail/type_mat.hpp \
		../glm/vec2.hpp \
		../glm/detail/type_vec2.hpp \
		../glm/detail/_swizzle.hpp \
		../glm/detail/_swizzle_func.hpp \
		../glm/detail/type_vec2.inl \
		../glm/vec3.hpp \
		../glm/detail/type_vec3.hpp \
		../glm/detail/type_vec3.inl \
		../glm/vec4.hpp \
		../glm/detail/type_vec4.hpp \
		../glm/detail/type_vec4.inl \
		../glm/detail/type_vec4_simd.inl \
		../glm/mat2x2.hpp \
		../glm/detail/type_mat2x2.hpp \
		../glm/detail/type_mat2x2.inl \
		../glm/detail/func_matrix.hpp \
		../glm/mat2x3.hpp \
		../glm/detail/type_mat2x3.hpp \
		../glm/detail/type_mat2x3.inl \
		../glm/mat2x4.hpp \
		../glm/detail/type_mat2x4.hpp \
		../glm/detail/type_mat2x4.inl \
		../glm/mat3x2.hpp \
		../glm/detail/type_mat3x2.hpp \
		../glm/detail/type_mat3x2.inl \
		../glm/mat3x3.hpp \
		../glm/detail/type_mat3x3.hpp \
		../glm/detail/type_mat3x3.inl \
		../glm/mat3x4.hpp \
		../glm/detail/type_mat3x4.hpp \
		../glm/detail/type_mat3x4.inl \
		../glm/mat4x2.hpp \
		../glm/detail/type_mat4x2.hpp \
		../glm/detail/type_mat4x2.inl \
		../glm/mat4x3.hpp \
		../glm/detail/type_mat4x3.hpp \
		../glm/detail/type_mat4x3.inl \
		../glm/mat4x4.hpp \
		../glm/detail/type_mat4x4.hpp \
		../glm/detail/type_mat4x4.inl \
		../glm/detail/type_mat4x4_simd.inl \
		../glm/detail/func_matrix.inl \
		../glm/geometric.hpp \
		../glm/detail/func_geometric.hpp \
		../glm/detail/func_geometric.inl \
		../glm/detail/func_exponential.hpp \
		../glm/detail/type_vec1.hpp \
		../glm/detail/type_vec1.inl \
		../glm/detail/func_exponential.inl \
		../glm/detail/func_vector_relational.hpp \
		../glm/detail/func_vector_relational.inl \
		../glm/detail/func_vector_relational_simd.inl \
		../glm/detail/_vectorize.hpp \
		../glm/detail/func_exponential_simd.inl \
		../glm/simd/exponential.h \
		../glm/detail/func_common.hpp \
		../glm/detail/func_common.inl \
		../glm/detail/func_common_simd.inl \
		../glm/simd/common.h \
		../glm/detail/func_geometric_simd.inl \
		../glm/simd/geometric.h \
		../glm/detail/func_matrix_simd.inl \
		../glm/simd/matrix.h \
		../glm/trigonometric.hpp \
		../glm/detail/func_trigonometric.hpp \
		../glm/detail/func_trigonometric.inl \
		../glm/detail/func_trigonometric_simd.inl \
		../glm/exponential.hpp \
		../glm/common.hpp \
		../glm/packing.hpp \
		../glm/detail/func_packing.hpp \
		../glm/detail/func_packing.inl \
		../glm/detail/type_half.hpp \
		../glm/detail/type_half.inl \
		../glm/detail/func_packing_simd.inl \
		../glm/matrix.hpp \
		../glm/vector_relational.hpp \
		../glm/integer.hpp \
		../glm/detail/func_integer.hpp \
		../glm/detail/func_integer.inl \
		../glm/detail/func_integer_simd.inl \
		../glm/simd/integer.h \
		../glm/gtc/matrix_transform.hpp \
		../glm/gtc/constants.hpp \
		../glm/gtc/constants.inl \
		../glm/gtc/matrix_transform.inl \
		../glm/gtx/string_cast.hpp \
		../glm/gtc/type_precision.hpp \
		../glm/gtc/quaternion.hpp \
		../glm/gtc/quaternion.inl \
		../glm/gtc/quaternion_simd.inl \
		../glm/gtc/vec1.hpp \
		../glm/gtc/vec1.inl \
		../glm/gtc/type_precision.inl \
		../glm/gtx/dual_quaternion.hpp \
		../glm/gtx/dual_quaternion.inl \
		../glm/gtx/string_cast.inl \
		include/Mesh.h \
		../glm/gtc/type_ptr.hpp \
		../glm/gtc/type_ptr.inl \
		../glm/ext.hpp \
		../glm/gtc/bitfield.hpp \
		../glm/gtc/bitfield.inl \
		../glm/gtc/color_space.hpp \
		../glm/gtc/color_space.inl \
		../glm/gtc/epsilon.hpp \
		../glm/gtc/epsilon.inl \
		../glm/gtc/functions.hpp \
		../glm/gtc/functions.inl \
		../glm/gtc/integer.hpp \
		../glm/gtc/integer.inl \
		../glm/gtc/matrix_access.hpp \
		../glm/gtc/matrix_access.inl \
		../glm/gtc/matrix_integer.hpp \
		../glm/gtc/matrix_inverse.hpp \
		../glm/gtc/matrix_inverse.inl \
		../glm/gtc/noise.hpp \
		../glm/detail/_noise.hpp \
		../glm/gtc/noise.inl \
		../glm/gtc/packing.hpp \
		../glm/gtc/packing.inl \
		../glm/gtc/random.hpp \
		../glm/gtc/random.inl \
		../glm/gtc/reciprocal.hpp \
		../glm/gtc/reciprocal.inl \
		../glm/gtc/round.hpp \
		../glm/gtc/round.inl \
		../glm/gtc/ulp.hpp \
		../glm/gtc/ulp.inl \
		../glm/gtc/type_aligned.hpp \
		../glm/gtx/associated_min_max.hpp \
		../glm/gtx/associated_min_max.inl \
		../glm/gtx/bit.hpp \
		../glm/gtx/bit.inl \
		../glm/gtx/closest_point.hpp \
		../glm/gtx/closest_point.inl \
		../glm/gtx/color_space.hpp \
		../glm/gtx/color_space_YCoCg.hpp \
		../glm/gtx/color_space_YCoCg.inl \
		../glm/gtx/compatibility.hpp \
		../glm/gtx/compatibility.inl \
		../glm/gtx/component_wise.hpp \
		../glm/gtx/component_wise.inl \
		../glm/gtx/euler_angles.hpp \
		../glm/gtx/euler_angles.inl \
		../glm/gtx/extend.hpp \
		../glm/gtx/extend.inl \
		../glm/gtx/extended_min_max.hpp \
		../glm/gtx/extended_min_max.inl \
		../glm/gtx/fast_exponential.hpp \
		../glm/gtx/fast_exponential.inl \
		../glm/gtx/fast_square_root.hpp \
		../glm/gtx/fast_square_root.inl \
		../glm/gtx/fast_trigonometry.hpp \
		../glm/gtx/fast_trigonometry.inl \
		../glm/gtx/gradient_paint.hpp \
		../glm/gtx/optimum_pow.hpp \
		../glm/gtx/optimum_pow.inl \
		../glm/gtx/gradient_paint.inl \
		../glm/gtx/handed_coordinate_space.hpp \
		../glm/gtx/handed_coordinate_space.inl \
		../glm/gtx/integer.hpp \
		../glm/gtx/intersect.hpp \
		../glm/gtx/vector_query.hpp \
		../glm/gtx/vector_query.inl \
		../glm/gtx/intersect.inl \
		../glm/gtx/log_base.hpp \
		../glm/gtx/log_base.inl \
		../glm/gtx/matrix_cross_product.hpp \
		../glm/gtx/matrix_cross_product.inl \
		../glm/gtx/matrix_interpolation.hpp \
		../glm/gtx/matrix_interpolation.inl \
		../glm/gtx/matrix_major_storage.hpp \
		../glm/gtx/matrix_major_storage.inl \
		../glm/gtx/matrix_operation.hpp \
		../glm/gtx/matrix_operation.inl \
		../glm/gtx/matrix_query.hpp \
		../glm/gtx/matrix_query.inl \
		../glm/gtx/mixed_product.hpp \
		../glm/gtx/mixed_product.inl \
		../glm/gtx/norm.hpp \
		../glm/gtx/quaternion.hpp \
		../glm/gtx/norm.inl \
		../glm/gtx/normal.hpp \
		../glm/gtx/normal.inl \
		../glm/gtx/normalize_dot.hpp \
		../glm/gtx/normalize_dot.inl \
		../glm/gtx/number_precision.hpp \
		../glm/gtx/number_precision.inl \
		../glm/gtx/orthonormalize.hpp \
		../glm/gtx/orthonormalize.inl \
		../glm/gtx/perpendicular.hpp \
		../glm/gtx/projection.hpp \
		../glm/gtx/projection.inl \
		../glm/gtx/perpendicular.inl \
		../glm/gtx/polar_coordinates.hpp \
		../glm/gtx/polar_coordinates.inl \
		../glm/gtx/raw_data.hpp \
		../glm/gtx/raw_data.inl \
		../glm/gtx/rotate_vector.hpp \
		../glm/gtx/transform.hpp \
		../glm/gtx/transform.inl \
		../glm/gtx/rotate_vector.inl \
		../glm/gtx/spline.hpp \
		../glm/gtx/spline.inl \
		../glm/gtx/std_based_type.hpp \
		../glm/gtx/std_based_type.inl \
		../glm/gtx/transform2.hpp \
		../glm/gtx/transform2.inl \
		../glm/gtx/vector_angle.hpp \
		../glm/gtx/vector_angle.inl \
		../glm/gtx/wrap.hpp \
		../glm/gtx/wrap.inl \
		../glm/gtx/scalar_multiplication.hpp \
		../glm/gtx/range.hpp \
		include/Buffer.h \
		include/marchingcube.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/main.o src/main.cpp

obj/MainWindow.o: src/MainWindow.cpp include/MainWindow.h \
		include/GLWindow.h \
		include/Shader.h \
		include/TrackballCamera.h \
		include/Camera.h \
		../glm/glm.hpp \
		../glm/detail/_fixes.hpp \
		../glm/fwd.hpp \
		../glm/detail/type_int.hpp \
		../glm/detail/setup.hpp \
		../glm/simd/platform.h \
		../glm/detail/type_float.hpp \
		../glm/detail/type_vec.hpp \
		../glm/detail/precision.hpp \
		../glm/detail/type_mat.hpp \
		../glm/vec2.hpp \
		../glm/detail/type_vec2.hpp \
		../glm/detail/_swizzle.hpp \
		../glm/detail/_swizzle_func.hpp \
		../glm/detail/type_vec2.inl \
		../glm/vec3.hpp \
		../glm/detail/type_vec3.hpp \
		../glm/detail/type_vec3.inl \
		../glm/vec4.hpp \
		../glm/detail/type_vec4.hpp \
		../glm/detail/type_vec4.inl \
		../glm/detail/type_vec4_simd.inl \
		../glm/mat2x2.hpp \
		../glm/detail/type_mat2x2.hpp \
		../glm/detail/type_mat2x2.inl \
		../glm/detail/func_matrix.hpp \
		../glm/mat2x3.hpp \
		../glm/detail/type_mat2x3.hpp \
		../glm/detail/type_mat2x3.inl \
		../glm/mat2x4.hpp \
		../glm/detail/type_mat2x4.hpp \
		../glm/detail/type_mat2x4.inl \
		../glm/mat3x2.hpp \
		../glm/detail/type_mat3x2.hpp \
		../glm/detail/type_mat3x2.inl \
		../glm/mat3x3.hpp \
		../glm/detail/type_mat3x3.hpp \
		../glm/detail/type_mat3x3.inl \
		../glm/mat3x4.hpp \
		../glm/detail/type_mat3x4.hpp \
		../glm/detail/type_mat3x4.inl \
		../glm/mat4x2.hpp \
		../glm/detail/type_mat4x2.hpp \
		../glm/detail/type_mat4x2.inl \
		../glm/mat4x3.hpp \
		../glm/detail/type_mat4x3.hpp \
		../glm/detail/type_mat4x3.inl \
		../glm/mat4x4.hpp \
		../glm/detail/type_mat4x4.hpp \
		../glm/detail/type_mat4x4.inl \
		../glm/detail/type_mat4x4_simd.inl \
		../glm/detail/func_matrix.inl \
		../glm/geometric.hpp \
		../glm/detail/func_geometric.hpp \
		../glm/detail/func_geometric.inl \
		../glm/detail/func_exponential.hpp \
		../glm/detail/type_vec1.hpp \
		../glm/detail/type_vec1.inl \
		../glm/detail/func_exponential.inl \
		../glm/detail/func_vector_relational.hpp \
		../glm/detail/func_vector_relational.inl \
		../glm/detail/func_vector_relational_simd.inl \
		../glm/detail/_vectorize.hpp \
		../glm/detail/func_exponential_simd.inl \
		../glm/simd/exponential.h \
		../glm/detail/func_common.hpp \
		../glm/detail/func_common.inl \
		../glm/detail/func_common_simd.inl \
		../glm/simd/common.h \
		../glm/detail/func_geometric_simd.inl \
		../glm/simd/geometric.h \
		../glm/detail/func_matrix_simd.inl \
		../glm/simd/matrix.h \
		../glm/trigonometric.hpp \
		../glm/detail/func_trigonometric.hpp \
		../glm/detail/func_trigonometric.inl \
		../glm/detail/func_trigonometric_simd.inl \
		../glm/exponential.hpp \
		../glm/common.hpp \
		../glm/packing.hpp \
		../glm/detail/func_packing.hpp \
		../glm/detail/func_packing.inl \
		../glm/detail/type_half.hpp \
		../glm/detail/type_half.inl \
		../glm/detail/func_packing_simd.inl \
		../glm/matrix.hpp \
		../glm/vector_relational.hpp \
		../glm/integer.hpp \
		../glm/detail/func_integer.hpp \
		../glm/detail/func_integer.inl \
		../glm/detail/func_integer_simd.inl \
		../glm/simd/integer.h \
		../glm/gtc/matrix_transform.hpp \
		../glm/gtc/constants.hpp \
		../glm/gtc/constants.inl \
		../glm/gtc/matrix_transform.inl \
		../glm/gtx/string_cast.hpp \
		../glm/gtc/type_precision.hpp \
		../glm/gtc/quaternion.hpp \
		../glm/gtc/quaternion.inl \
		../glm/gtc/quaternion_simd.inl \
		../glm/gtc/vec1.hpp \
		../glm/gtc/vec1.inl \
		../glm/gtc/type_precision.inl \
		../glm/gtx/dual_quaternion.hpp \
		../glm/gtx/dual_quaternion.inl \
		../glm/gtx/string_cast.inl \
		include/Mesh.h \
		../glm/gtc/type_ptr.hpp \
		../glm/gtc/type_ptr.inl \
		../glm/ext.hpp \
		../glm/gtc/bitfield.hpp \
		../glm/gtc/bitfield.inl \
		../glm/gtc/color_space.hpp \
		../glm/gtc/color_space.inl \
		../glm/gtc/epsilon.hpp \
		../glm/gtc/epsilon.inl \
		../glm/gtc/functions.hpp \
		../glm/gtc/functions.inl \
		../glm/gtc/integer.hpp \
		../glm/gtc/integer.inl \
		../glm/gtc/matrix_access.hpp \
		../glm/gtc/matrix_access.inl \
		../glm/gtc/matrix_integer.hpp \
		../glm/gtc/matrix_inverse.hpp \
		../glm/gtc/matrix_inverse.inl \
		../glm/gtc/noise.hpp \
		../glm/detail/_noise.hpp \
		../glm/gtc/noise.inl \
		../glm/gtc/packing.hpp \
		../glm/gtc/packing.inl \
		../glm/gtc/random.hpp \
		../glm/gtc/random.inl \
		../glm/gtc/reciprocal.hpp \
		../glm/gtc/reciprocal.inl \
		../glm/gtc/round.hpp \
		../glm/gtc/round.inl \
		../glm/gtc/ulp.hpp \
		../glm/gtc/ulp.inl \
		../glm/gtc/type_aligned.hpp \
		../glm/gtx/associated_min_max.hpp \
		../glm/gtx/associated_min_max.inl \
		../glm/gtx/bit.hpp \
		../glm/gtx/bit.inl \
		../glm/gtx/closest_point.hpp \
		../glm/gtx/closest_point.inl \
		../glm/gtx/color_space.hpp \
		../glm/gtx/color_space_YCoCg.hpp \
		../glm/gtx/color_space_YCoCg.inl \
		../glm/gtx/compatibility.hpp \
		../glm/gtx/compatibility.inl \
		../glm/gtx/component_wise.hpp \
		../glm/gtx/component_wise.inl \
		../glm/gtx/euler_angles.hpp \
		../glm/gtx/euler_angles.inl \
		../glm/gtx/extend.hpp \
		../glm/gtx/extend.inl \
		../glm/gtx/extended_min_max.hpp \
		../glm/gtx/extended_min_max.inl \
		../glm/gtx/fast_exponential.hpp \
		../glm/gtx/fast_exponential.inl \
		../glm/gtx/fast_square_root.hpp \
		../glm/gtx/fast_square_root.inl \
		../glm/gtx/fast_trigonometry.hpp \
		../glm/gtx/fast_trigonometry.inl \
		../glm/gtx/gradient_paint.hpp \
		../glm/gtx/optimum_pow.hpp \
		../glm/gtx/optimum_pow.inl \
		../glm/gtx/gradient_paint.inl \
		../glm/gtx/handed_coordinate_space.hpp \
		../glm/gtx/handed_coordinate_space.inl \
		../glm/gtx/integer.hpp \
		../glm/gtx/intersect.hpp \
		../glm/gtx/vector_query.hpp \
		../glm/gtx/vector_query.inl \
		../glm/gtx/intersect.inl \
		../glm/gtx/log_base.hpp \
		../glm/gtx/log_base.inl \
		../glm/gtx/matrix_cross_product.hpp \
		../glm/gtx/matrix_cross_product.inl \
		../glm/gtx/matrix_interpolation.hpp \
		../glm/gtx/matrix_interpolation.inl \
		../glm/gtx/matrix_major_storage.hpp \
		../glm/gtx/matrix_major_storage.inl \
		../glm/gtx/matrix_operation.hpp \
		../glm/gtx/matrix_operation.inl \
		../glm/gtx/matrix_query.hpp \
		../glm/gtx/matrix_query.inl \
		../glm/gtx/mixed_product.hpp \
		../glm/gtx/mixed_product.inl \
		../glm/gtx/norm.hpp \
		../glm/gtx/quaternion.hpp \
		../glm/gtx/norm.inl \
		../glm/gtx/normal.hpp \
		../glm/gtx/normal.inl \
		../glm/gtx/normalize_dot.hpp \
		../glm/gtx/normalize_dot.inl \
		../glm/gtx/number_precision.hpp \
		../glm/gtx/number_precision.inl \
		../glm/gtx/orthonormalize.hpp \
		../glm/gtx/orthonormalize.inl \
		../glm/gtx/perpendicular.hpp \
		../glm/gtx/projection.hpp \
		../glm/gtx/projection.inl \
		../glm/gtx/perpendicular.inl \
		../glm/gtx/polar_coordinates.hpp \
		../glm/gtx/polar_coordinates.inl \
		../glm/gtx/raw_data.hpp \
		../glm/gtx/raw_data.inl \
		../glm/gtx/rotate_vector.hpp \
		../glm/gtx/transform.hpp \
		../glm/gtx/transform.inl \
		../glm/gtx/rotate_vector.inl \
		../glm/gtx/spline.hpp \
		../glm/gtx/spline.inl \
		../glm/gtx/std_based_type.hpp \
		../glm/gtx/std_based_type.inl \
		../glm/gtx/transform2.hpp \
		../glm/gtx/transform2.inl \
		../glm/gtx/vector_angle.hpp \
		../glm/gtx/vector_angle.inl \
		../glm/gtx/wrap.hpp \
		../glm/gtx/wrap.inl \
		../glm/gtx/scalar_multiplication.hpp \
		../glm/gtx/range.hpp \
		include/Buffer.h \
		include/marchingcube.h \
		ui/ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/MainWindow.o src/MainWindow.cpp

obj/GLWindow.o: src/GLWindow.cpp include/GLWindow.h \
		include/Shader.h \
		include/TrackballCamera.h \
		include/Camera.h \
		../glm/glm.hpp \
		../glm/detail/_fixes.hpp \
		../glm/fwd.hpp \
		../glm/detail/type_int.hpp \
		../glm/detail/setup.hpp \
		../glm/simd/platform.h \
		../glm/detail/type_float.hpp \
		../glm/detail/type_vec.hpp \
		../glm/detail/precision.hpp \
		../glm/detail/type_mat.hpp \
		../glm/vec2.hpp \
		../glm/detail/type_vec2.hpp \
		../glm/detail/_swizzle.hpp \
		../glm/detail/_swizzle_func.hpp \
		../glm/detail/type_vec2.inl \
		../glm/vec3.hpp \
		../glm/detail/type_vec3.hpp \
		../glm/detail/type_vec3.inl \
		../glm/vec4.hpp \
		../glm/detail/type_vec4.hpp \
		../glm/detail/type_vec4.inl \
		../glm/detail/type_vec4_simd.inl \
		../glm/mat2x2.hpp \
		../glm/detail/type_mat2x2.hpp \
		../glm/detail/type_mat2x2.inl \
		../glm/detail/func_matrix.hpp \
		../glm/mat2x3.hpp \
		../glm/detail/type_mat2x3.hpp \
		../glm/detail/type_mat2x3.inl \
		../glm/mat2x4.hpp \
		../glm/detail/type_mat2x4.hpp \
		../glm/detail/type_mat2x4.inl \
		../glm/mat3x2.hpp \
		../glm/detail/type_mat3x2.hpp \
		../glm/detail/type_mat3x2.inl \
		../glm/mat3x3.hpp \
		../glm/detail/type_mat3x3.hpp \
		../glm/detail/type_mat3x3.inl \
		../glm/mat3x4.hpp \
		../glm/detail/type_mat3x4.hpp \
		../glm/detail/type_mat3x4.inl \
		../glm/mat4x2.hpp \
		../glm/detail/type_mat4x2.hpp \
		../glm/detail/type_mat4x2.inl \
		../glm/mat4x3.hpp \
		../glm/detail/type_mat4x3.hpp \
		../glm/detail/type_mat4x3.inl \
		../glm/mat4x4.hpp \
		../glm/detail/type_mat4x4.hpp \
		../glm/detail/type_mat4x4.inl \
		../glm/detail/type_mat4x4_simd.inl \
		../glm/detail/func_matrix.inl \
		../glm/geometric.hpp \
		../glm/detail/func_geometric.hpp \
		../glm/detail/func_geometric.inl \
		../glm/detail/func_exponential.hpp \
		../glm/detail/type_vec1.hpp \
		../glm/detail/type_vec1.inl \
		../glm/detail/func_exponential.inl \
		../glm/detail/func_vector_relational.hpp \
		../glm/detail/func_vector_relational.inl \
		../glm/detail/func_vector_relational_simd.inl \
		../glm/detail/_vectorize.hpp \
		../glm/detail/func_exponential_simd.inl \
		../glm/simd/exponential.h \
		../glm/detail/func_common.hpp \
		../glm/detail/func_common.inl \
		../glm/detail/func_common_simd.inl \
		../glm/simd/common.h \
		../glm/detail/func_geometric_simd.inl \
		../glm/simd/geometric.h \
		../glm/detail/func_matrix_simd.inl \
		../glm/simd/matrix.h \
		../glm/trigonometric.hpp \
		../glm/detail/func_trigonometric.hpp \
		../glm/detail/func_trigonometric.inl \
		../glm/detail/func_trigonometric_simd.inl \
		../glm/exponential.hpp \
		../glm/common.hpp \
		../glm/packing.hpp \
		../glm/detail/func_packing.hpp \
		../glm/detail/func_packing.inl \
		../glm/detail/type_half.hpp \
		../glm/detail/type_half.inl \
		../glm/detail/func_packing_simd.inl \
		../glm/matrix.hpp \
		../glm/vector_relational.hpp \
		../glm/integer.hpp \
		../glm/detail/func_integer.hpp \
		../glm/detail/func_integer.inl \
		../glm/detail/func_integer_simd.inl \
		../glm/simd/integer.h \
		../glm/gtc/matrix_transform.hpp \
		../glm/gtc/constants.hpp \
		../glm/gtc/constants.inl \
		../glm/gtc/matrix_transform.inl \
		../glm/gtx/string_cast.hpp \
		../glm/gtc/type_precision.hpp \
		../glm/gtc/quaternion.hpp \
		../glm/gtc/quaternion.inl \
		../glm/gtc/quaternion_simd.inl \
		../glm/gtc/vec1.hpp \
		../glm/gtc/vec1.inl \
		../glm/gtc/type_precision.inl \
		../glm/gtx/dual_quaternion.hpp \
		../glm/gtx/dual_quaternion.inl \
		../glm/gtx/string_cast.inl \
		include/Mesh.h \
		../glm/gtc/type_ptr.hpp \
		../glm/gtc/type_ptr.inl \
		../glm/ext.hpp \
		../glm/gtc/bitfield.hpp \
		../glm/gtc/bitfield.inl \
		../glm/gtc/color_space.hpp \
		../glm/gtc/color_space.inl \
		../glm/gtc/epsilon.hpp \
		../glm/gtc/epsilon.inl \
		../glm/gtc/functions.hpp \
		../glm/gtc/functions.inl \
		../glm/gtc/integer.hpp \
		../glm/gtc/integer.inl \
		../glm/gtc/matrix_access.hpp \
		../glm/gtc/matrix_access.inl \
		../glm/gtc/matrix_integer.hpp \
		../glm/gtc/matrix_inverse.hpp \
		../glm/gtc/matrix_inverse.inl \
		../glm/gtc/noise.hpp \
		../glm/detail/_noise.hpp \
		../glm/gtc/noise.inl \
		../glm/gtc/packing.hpp \
		../glm/gtc/packing.inl \
		../glm/gtc/random.hpp \
		../glm/gtc/random.inl \
		../glm/gtc/reciprocal.hpp \
		../glm/gtc/reciprocal.inl \
		../glm/gtc/round.hpp \
		../glm/gtc/round.inl \
		../glm/gtc/ulp.hpp \
		../glm/gtc/ulp.inl \
		../glm/gtc/type_aligned.hpp \
		../glm/gtx/associated_min_max.hpp \
		../glm/gtx/associated_min_max.inl \
		../glm/gtx/bit.hpp \
		../glm/gtx/bit.inl \
		../glm/gtx/closest_point.hpp \
		../glm/gtx/closest_point.inl \
		../glm/gtx/color_space.hpp \
		../glm/gtx/color_space_YCoCg.hpp \
		../glm/gtx/color_space_YCoCg.inl \
		../glm/gtx/compatibility.hpp \
		../glm/gtx/compatibility.inl \
		../glm/gtx/component_wise.hpp \
		../glm/gtx/component_wise.inl \
		../glm/gtx/euler_angles.hpp \
		../glm/gtx/euler_angles.inl \
		../glm/gtx/extend.hpp \
		../glm/gtx/extend.inl \
		../glm/gtx/extended_min_max.hpp \
		../glm/gtx/extended_min_max.inl \
		../glm/gtx/fast_exponential.hpp \
		../glm/gtx/fast_exponential.inl \
		../glm/gtx/fast_square_root.hpp \
		../glm/gtx/fast_square_root.inl \
		../glm/gtx/fast_trigonometry.hpp \
		../glm/gtx/fast_trigonometry.inl \
		../glm/gtx/gradient_paint.hpp \
		../glm/gtx/optimum_pow.hpp \
		../glm/gtx/optimum_pow.inl \
		../glm/gtx/gradient_paint.inl \
		../glm/gtx/handed_coordinate_space.hpp \
		../glm/gtx/handed_coordinate_space.inl \
		../glm/gtx/integer.hpp \
		../glm/gtx/intersect.hpp \
		../glm/gtx/vector_query.hpp \
		../glm/gtx/vector_query.inl \
		../glm/gtx/intersect.inl \
		../glm/gtx/log_base.hpp \
		../glm/gtx/log_base.inl \
		../glm/gtx/matrix_cross_product.hpp \
		../glm/gtx/matrix_cross_product.inl \
		../glm/gtx/matrix_interpolation.hpp \
		../glm/gtx/matrix_interpolation.inl \
		../glm/gtx/matrix_major_storage.hpp \
		../glm/gtx/matrix_major_storage.inl \
		../glm/gtx/matrix_operation.hpp \
		../glm/gtx/matrix_operation.inl \
		../glm/gtx/matrix_query.hpp \
		../glm/gtx/matrix_query.inl \
		../glm/gtx/mixed_product.hpp \
		../glm/gtx/mixed_product.inl \
		../glm/gtx/norm.hpp \
		../glm/gtx/quaternion.hpp \
		../glm/gtx/norm.inl \
		../glm/gtx/normal.hpp \
		../glm/gtx/normal.inl \
		../glm/gtx/normalize_dot.hpp \
		../glm/gtx/normalize_dot.inl \
		../glm/gtx/number_precision.hpp \
		../glm/gtx/number_precision.inl \
		../glm/gtx/orthonormalize.hpp \
		../glm/gtx/orthonormalize.inl \
		../glm/gtx/perpendicular.hpp \
		../glm/gtx/projection.hpp \
		../glm/gtx/projection.inl \
		../glm/gtx/perpendicular.inl \
		../glm/gtx/polar_coordinates.hpp \
		../glm/gtx/polar_coordinates.inl \
		../glm/gtx/raw_data.hpp \
		../glm/gtx/raw_data.inl \
		../glm/gtx/rotate_vector.hpp \
		../glm/gtx/transform.hpp \
		../glm/gtx/transform.inl \
		../glm/gtx/rotate_vector.inl \
		../glm/gtx/spline.hpp \
		../glm/gtx/spline.inl \
		../glm/gtx/std_based_type.hpp \
		../glm/gtx/std_based_type.inl \
		../glm/gtx/transform2.hpp \
		../glm/gtx/transform2.inl \
		../glm/gtx/vector_angle.hpp \
		../glm/gtx/vector_angle.inl \
		../glm/gtx/wrap.hpp \
		../glm/gtx/wrap.inl \
		../glm/gtx/scalar_multiplication.hpp \
		../glm/gtx/range.hpp \
		include/Buffer.h \
		include/marchingcube.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/GLWindow.o src/GLWindow.cpp

obj/Camera.o: src/Camera.cpp include/Camera.h \
		../glm/glm.hpp \
		../glm/detail/_fixes.hpp \
		../glm/fwd.hpp \
		../glm/detail/type_int.hpp \
		../glm/detail/setup.hpp \
		../glm/simd/platform.h \
		../glm/detail/type_float.hpp \
		../glm/detail/type_vec.hpp \
		../glm/detail/precision.hpp \
		../glm/detail/type_mat.hpp \
		../glm/vec2.hpp \
		../glm/detail/type_vec2.hpp \
		../glm/detail/_swizzle.hpp \
		../glm/detail/_swizzle_func.hpp \
		../glm/detail/type_vec2.inl \
		../glm/vec3.hpp \
		../glm/detail/type_vec3.hpp \
		../glm/detail/type_vec3.inl \
		../glm/vec4.hpp \
		../glm/detail/type_vec4.hpp \
		../glm/detail/type_vec4.inl \
		../glm/detail/type_vec4_simd.inl \
		../glm/mat2x2.hpp \
		../glm/detail/type_mat2x2.hpp \
		../glm/detail/type_mat2x2.inl \
		../glm/detail/func_matrix.hpp \
		../glm/mat2x3.hpp \
		../glm/detail/type_mat2x3.hpp \
		../glm/detail/type_mat2x3.inl \
		../glm/mat2x4.hpp \
		../glm/detail/type_mat2x4.hpp \
		../glm/detail/type_mat2x4.inl \
		../glm/mat3x2.hpp \
		../glm/detail/type_mat3x2.hpp \
		../glm/detail/type_mat3x2.inl \
		../glm/mat3x3.hpp \
		../glm/detail/type_mat3x3.hpp \
		../glm/detail/type_mat3x3.inl \
		../glm/mat3x4.hpp \
		../glm/detail/type_mat3x4.hpp \
		../glm/detail/type_mat3x4.inl \
		../glm/mat4x2.hpp \
		../glm/detail/type_mat4x2.hpp \
		../glm/detail/type_mat4x2.inl \
		../glm/mat4x3.hpp \
		../glm/detail/type_mat4x3.hpp \
		../glm/detail/type_mat4x3.inl \
		../glm/mat4x4.hpp \
		../glm/detail/type_mat4x4.hpp \
		../glm/detail/type_mat4x4.inl \
		../glm/detail/type_mat4x4_simd.inl \
		../glm/detail/func_matrix.inl \
		../glm/geometric.hpp \
		../glm/detail/func_geometric.hpp \
		../glm/detail/func_geometric.inl \
		../glm/detail/func_exponential.hpp \
		../glm/detail/type_vec1.hpp \
		../glm/detail/type_vec1.inl \
		../glm/detail/func_exponential.inl \
		../glm/detail/func_vector_relational.hpp \
		../glm/detail/func_vector_relational.inl \
		../glm/detail/func_vector_relational_simd.inl \
		../glm/detail/_vectorize.hpp \
		../glm/detail/func_exponential_simd.inl \
		../glm/simd/exponential.h \
		../glm/detail/func_common.hpp \
		../glm/detail/func_common.inl \
		../glm/detail/func_common_simd.inl \
		../glm/simd/common.h \
		../glm/detail/func_geometric_simd.inl \
		../glm/simd/geometric.h \
		../glm/detail/func_matrix_simd.inl \
		../glm/simd/matrix.h \
		../glm/trigonometric.hpp \
		../glm/detail/func_trigonometric.hpp \
		../glm/detail/func_trigonometric.inl \
		../glm/detail/func_trigonometric_simd.inl \
		../glm/exponential.hpp \
		../glm/common.hpp \
		../glm/packing.hpp \
		../glm/detail/func_packing.hpp \
		../glm/detail/func_packing.inl \
		../glm/detail/type_half.hpp \
		../glm/detail/type_half.inl \
		../glm/detail/func_packing_simd.inl \
		../glm/matrix.hpp \
		../glm/vector_relational.hpp \
		../glm/integer.hpp \
		../glm/detail/func_integer.hpp \
		../glm/detail/func_integer.inl \
		../glm/detail/func_integer_simd.inl \
		../glm/simd/integer.h \
		../glm/gtc/matrix_transform.hpp \
		../glm/gtc/constants.hpp \
		../glm/gtc/constants.inl \
		../glm/gtc/matrix_transform.inl \
		../glm/gtx/string_cast.hpp \
		../glm/gtc/type_precision.hpp \
		../glm/gtc/quaternion.hpp \
		../glm/gtc/quaternion.inl \
		../glm/gtc/quaternion_simd.inl \
		../glm/gtc/vec1.hpp \
		../glm/gtc/vec1.inl \
		../glm/gtc/type_precision.inl \
		../glm/gtx/dual_quaternion.hpp \
		../glm/gtx/dual_quaternion.inl \
		../glm/gtx/string_cast.inl
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Camera.o src/Camera.cpp

obj/TrackballCamera.o: src/TrackballCamera.cpp include/TrackballCamera.h \
		include/Camera.h \
		../glm/glm.hpp \
		../glm/detail/_fixes.hpp \
		../glm/fwd.hpp \
		../glm/detail/type_int.hpp \
		../glm/detail/setup.hpp \
		../glm/simd/platform.h \
		../glm/detail/type_float.hpp \
		../glm/detail/type_vec.hpp \
		../glm/detail/precision.hpp \
		../glm/detail/type_mat.hpp \
		../glm/vec2.hpp \
		../glm/detail/type_vec2.hpp \
		../glm/detail/_swizzle.hpp \
		../glm/detail/_swizzle_func.hpp \
		../glm/detail/type_vec2.inl \
		../glm/vec3.hpp \
		../glm/detail/type_vec3.hpp \
		../glm/detail/type_vec3.inl \
		../glm/vec4.hpp \
		../glm/detail/type_vec4.hpp \
		../glm/detail/type_vec4.inl \
		../glm/detail/type_vec4_simd.inl \
		../glm/mat2x2.hpp \
		../glm/detail/type_mat2x2.hpp \
		../glm/detail/type_mat2x2.inl \
		../glm/detail/func_matrix.hpp \
		../glm/mat2x3.hpp \
		../glm/detail/type_mat2x3.hpp \
		../glm/detail/type_mat2x3.inl \
		../glm/mat2x4.hpp \
		../glm/detail/type_mat2x4.hpp \
		../glm/detail/type_mat2x4.inl \
		../glm/mat3x2.hpp \
		../glm/detail/type_mat3x2.hpp \
		../glm/detail/type_mat3x2.inl \
		../glm/mat3x3.hpp \
		../glm/detail/type_mat3x3.hpp \
		../glm/detail/type_mat3x3.inl \
		../glm/mat3x4.hpp \
		../glm/detail/type_mat3x4.hpp \
		../glm/detail/type_mat3x4.inl \
		../glm/mat4x2.hpp \
		../glm/detail/type_mat4x2.hpp \
		../glm/detail/type_mat4x2.inl \
		../glm/mat4x3.hpp \
		../glm/detail/type_mat4x3.hpp \
		../glm/detail/type_mat4x3.inl \
		../glm/mat4x4.hpp \
		../glm/detail/type_mat4x4.hpp \
		../glm/detail/type_mat4x4.inl \
		../glm/detail/type_mat4x4_simd.inl \
		../glm/detail/func_matrix.inl \
		../glm/geometric.hpp \
		../glm/detail/func_geometric.hpp \
		../glm/detail/func_geometric.inl \
		../glm/detail/func_exponential.hpp \
		../glm/detail/type_vec1.hpp \
		../glm/detail/type_vec1.inl \
		../glm/detail/func_exponential.inl \
		../glm/detail/func_vector_relational.hpp \
		../glm/detail/func_vector_relational.inl \
		../glm/detail/func_vector_relational_simd.inl \
		../glm/detail/_vectorize.hpp \
		../glm/detail/func_exponential_simd.inl \
		../glm/simd/exponential.h \
		../glm/detail/func_common.hpp \
		../glm/detail/func_common.inl \
		../glm/detail/func_common_simd.inl \
		../glm/simd/common.h \
		../glm/detail/func_geometric_simd.inl \
		../glm/simd/geometric.h \
		../glm/detail/func_matrix_simd.inl \
		../glm/simd/matrix.h \
		../glm/trigonometric.hpp \
		../glm/detail/func_trigonometric.hpp \
		../glm/detail/func_trigonometric.inl \
		../glm/detail/func_trigonometric_simd.inl \
		../glm/exponential.hpp \
		../glm/common.hpp \
		../glm/packing.hpp \
		../glm/detail/func_packing.hpp \
		../glm/detail/func_packing.inl \
		../glm/detail/type_half.hpp \
		../glm/detail/type_half.inl \
		../glm/detail/func_packing_simd.inl \
		../glm/matrix.hpp \
		../glm/vector_relational.hpp \
		../glm/integer.hpp \
		../glm/detail/func_integer.hpp \
		../glm/detail/func_integer.inl \
		../glm/detail/func_integer_simd.inl \
		../glm/simd/integer.h \
		../glm/gtc/matrix_transform.hpp \
		../glm/gtc/constants.hpp \
		../glm/gtc/constants.inl \
		../glm/gtc/matrix_transform.inl \
		../glm/gtx/string_cast.hpp \
		../glm/gtc/type_precision.hpp \
		../glm/gtc/quaternion.hpp \
		../glm/gtc/quaternion.inl \
		../glm/gtc/quaternion_simd.inl \
		../glm/gtc/vec1.hpp \
		../glm/gtc/vec1.inl \
		../glm/gtc/type_precision.inl \
		../glm/gtx/dual_quaternion.hpp \
		../glm/gtx/dual_quaternion.inl \
		../glm/gtx/string_cast.inl \
		../glm/gtx/norm.hpp \
		../glm/gtx/quaternion.hpp \
		../glm/gtx/norm.inl
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/TrackballCamera.o src/TrackballCamera.cpp

obj/Shader.o: src/Shader.cpp include/Shader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Shader.o src/Shader.cpp

obj/Mesh.o: src/Mesh.cpp include/Mesh.h \
		../glm/glm.hpp \
		../glm/detail/_fixes.hpp \
		../glm/fwd.hpp \
		../glm/detail/type_int.hpp \
		../glm/detail/setup.hpp \
		../glm/simd/platform.h \
		../glm/detail/type_float.hpp \
		../glm/detail/type_vec.hpp \
		../glm/detail/precision.hpp \
		../glm/detail/type_mat.hpp \
		../glm/vec2.hpp \
		../glm/detail/type_vec2.hpp \
		../glm/detail/_swizzle.hpp \
		../glm/detail/_swizzle_func.hpp \
		../glm/detail/type_vec2.inl \
		../glm/vec3.hpp \
		../glm/detail/type_vec3.hpp \
		../glm/detail/type_vec3.inl \
		../glm/vec4.hpp \
		../glm/detail/type_vec4.hpp \
		../glm/detail/type_vec4.inl \
		../glm/detail/type_vec4_simd.inl \
		../glm/mat2x2.hpp \
		../glm/detail/type_mat2x2.hpp \
		../glm/detail/type_mat2x2.inl \
		../glm/detail/func_matrix.hpp \
		../glm/mat2x3.hpp \
		../glm/detail/type_mat2x3.hpp \
		../glm/detail/type_mat2x3.inl \
		../glm/mat2x4.hpp \
		../glm/detail/type_mat2x4.hpp \
		../glm/detail/type_mat2x4.inl \
		../glm/mat3x2.hpp \
		../glm/detail/type_mat3x2.hpp \
		../glm/detail/type_mat3x2.inl \
		../glm/mat3x3.hpp \
		../glm/detail/type_mat3x3.hpp \
		../glm/detail/type_mat3x3.inl \
		../glm/mat3x4.hpp \
		../glm/detail/type_mat3x4.hpp \
		../glm/detail/type_mat3x4.inl \
		../glm/mat4x2.hpp \
		../glm/detail/type_mat4x2.hpp \
		../glm/detail/type_mat4x2.inl \
		../glm/mat4x3.hpp \
		../glm/detail/type_mat4x3.hpp \
		../glm/detail/type_mat4x3.inl \
		../glm/mat4x4.hpp \
		../glm/detail/type_mat4x4.hpp \
		../glm/detail/type_mat4x4.inl \
		../glm/detail/type_mat4x4_simd.inl \
		../glm/detail/func_matrix.inl \
		../glm/geometric.hpp \
		../glm/detail/func_geometric.hpp \
		../glm/detail/func_geometric.inl \
		../glm/detail/func_exponential.hpp \
		../glm/detail/type_vec1.hpp \
		../glm/detail/type_vec1.inl \
		../glm/detail/func_exponential.inl \
		../glm/detail/func_vector_relational.hpp \
		../glm/detail/func_vector_relational.inl \
		../glm/detail/func_vector_relational_simd.inl \
		../glm/detail/_vectorize.hpp \
		../glm/detail/func_exponential_simd.inl \
		../glm/simd/exponential.h \
		../glm/detail/func_common.hpp \
		../glm/detail/func_common.inl \
		../glm/detail/func_common_simd.inl \
		../glm/simd/common.h \
		../glm/detail/func_geometric_simd.inl \
		../glm/simd/geometric.h \
		../glm/detail/func_matrix_simd.inl \
		../glm/simd/matrix.h \
		../glm/trigonometric.hpp \
		../glm/detail/func_trigonometric.hpp \
		../glm/detail/func_trigonometric.inl \
		../glm/detail/func_trigonometric_simd.inl \
		../glm/exponential.hpp \
		../glm/common.hpp \
		../glm/packing.hpp \
		../glm/detail/func_packing.hpp \
		../glm/detail/func_packing.inl \
		../glm/detail/type_half.hpp \
		../glm/detail/type_half.inl \
		../glm/detail/func_packing_simd.inl \
		../glm/matrix.hpp \
		../glm/vector_relational.hpp \
		../glm/integer.hpp \
		../glm/detail/func_integer.hpp \
		../glm/detail/func_integer.inl \
		../glm/detail/func_integer_simd.inl \
		../glm/simd/integer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Mesh.o src/Mesh.cpp

obj/Scene.o: src/Scene.cpp include/Scene.h \
		../glm/gtc/matrix_transform.hpp \
		../glm/mat4x4.hpp \
		../glm/detail/type_mat4x4.hpp \
		../glm/fwd.hpp \
		../glm/detail/type_int.hpp \
		../glm/detail/setup.hpp \
		../glm/simd/platform.h \
		../glm/detail/type_float.hpp \
		../glm/detail/type_vec.hpp \
		../glm/detail/precision.hpp \
		../glm/detail/type_mat.hpp \
		../glm/detail/type_vec4.hpp \
		../glm/detail/_swizzle.hpp \
		../glm/detail/_swizzle_func.hpp \
		../glm/detail/type_vec4.inl \
		../glm/detail/type_vec4_simd.inl \
		../glm/detail/type_mat4x4.inl \
		../glm/detail/func_matrix.hpp \
		../glm/vec2.hpp \
		../glm/detail/type_vec2.hpp \
		../glm/detail/type_vec2.inl \
		../glm/vec3.hpp \
		../glm/detail/type_vec3.hpp \
		../glm/detail/type_vec3.inl \
		../glm/vec4.hpp \
		../glm/mat2x2.hpp \
		../glm/detail/type_mat2x2.hpp \
		../glm/detail/type_mat2x2.inl \
		../glm/mat2x3.hpp \
		../glm/detail/type_mat2x3.hpp \
		../glm/detail/type_mat2x3.inl \
		../glm/mat2x4.hpp \
		../glm/detail/type_mat2x4.hpp \
		../glm/detail/type_mat2x4.inl \
		../glm/mat3x2.hpp \
		../glm/detail/type_mat3x2.hpp \
		../glm/detail/type_mat3x2.inl \
		../glm/mat3x3.hpp \
		../glm/detail/type_mat3x3.hpp \
		../glm/detail/type_mat3x3.inl \
		../glm/mat3x4.hpp \
		../glm/detail/type_mat3x4.hpp \
		../glm/detail/type_mat3x4.inl \
		../glm/mat4x2.hpp \
		../glm/detail/type_mat4x2.hpp \
		../glm/detail/type_mat4x2.inl \
		../glm/mat4x3.hpp \
		../glm/detail/type_mat4x3.hpp \
		../glm/detail/type_mat4x3.inl \
		../glm/detail/func_matrix.inl \
		../glm/geometric.hpp \
		../glm/detail/func_geometric.hpp \
		../glm/detail/func_geometric.inl \
		../glm/detail/func_exponential.hpp \
		../glm/detail/type_vec1.hpp \
		../glm/detail/type_vec1.inl \
		../glm/detail/func_exponential.inl \
		../glm/detail/func_vector_relational.hpp \
		../glm/detail/func_vector_relational.inl \
		../glm/detail/func_vector_relational_simd.inl \
		../glm/detail/_vectorize.hpp \
		../glm/detail/func_exponential_simd.inl \
		../glm/simd/exponential.h \
		../glm/detail/func_common.hpp \
		../glm/detail/_fixes.hpp \
		../glm/detail/func_common.inl \
		../glm/detail/func_common_simd.inl \
		../glm/simd/common.h \
		../glm/detail/func_geometric_simd.inl \
		../glm/simd/geometric.h \
		../glm/detail/func_matrix_simd.inl \
		../glm/simd/matrix.h \
		../glm/detail/type_mat4x4_simd.inl \
		../glm/gtc/constants.hpp \
		../glm/gtc/constants.inl \
		../glm/gtc/matrix_transform.inl \
		../glm/trigonometric.hpp \
		../glm/detail/func_trigonometric.hpp \
		../glm/detail/func_trigonometric.inl \
		../glm/detail/func_trigonometric_simd.inl \
		../glm/matrix.hpp \
		../glm/gtc/type_ptr.hpp \
		../glm/gtc/quaternion.hpp \
		../glm/gtc/quaternion.inl \
		../glm/exponential.hpp \
		../glm/gtc/quaternion_simd.inl \
		../glm/gtc/type_ptr.inl \
		../glm/ext.hpp \
		../glm/glm.hpp \
		../glm/common.hpp \
		../glm/packing.hpp \
		../glm/detail/func_packing.hpp \
		../glm/detail/func_packing.inl \
		../glm/detail/type_half.hpp \
		../glm/detail/type_half.inl \
		../glm/detail/func_packing_simd.inl \
		../glm/vector_relational.hpp \
		../glm/integer.hpp \
		../glm/detail/func_integer.hpp \
		../glm/detail/func_integer.inl \
		../glm/detail/func_integer_simd.inl \
		../glm/simd/integer.h \
		../glm/gtc/bitfield.hpp \
		../glm/gtc/bitfield.inl \
		../glm/gtc/color_space.hpp \
		../glm/gtc/color_space.inl \
		../glm/gtc/epsilon.hpp \
		../glm/gtc/epsilon.inl \
		../glm/gtc/functions.hpp \
		../glm/gtc/functions.inl \
		../glm/gtc/integer.hpp \
		../glm/gtc/integer.inl \
		../glm/gtc/matrix_access.hpp \
		../glm/gtc/matrix_access.inl \
		../glm/gtc/matrix_integer.hpp \
		../glm/gtc/matrix_inverse.hpp \
		../glm/gtc/matrix_inverse.inl \
		../glm/gtc/noise.hpp \
		../glm/detail/_noise.hpp \
		../glm/gtc/noise.inl \
		../glm/gtc/packing.hpp \
		../glm/gtc/type_precision.hpp \
		../glm/gtc/vec1.hpp \
		../glm/gtc/vec1.inl \
		../glm/gtc/type_precision.inl \
		../glm/gtc/packing.inl \
		../glm/gtc/random.hpp \
		../glm/gtc/random.inl \
		../glm/gtc/reciprocal.hpp \
		../glm/gtc/reciprocal.inl \
		../glm/gtc/round.hpp \
		../glm/gtc/round.inl \
		../glm/gtc/ulp.hpp \
		../glm/gtc/ulp.inl \
		../glm/gtc/type_aligned.hpp \
		../glm/gtx/associated_min_max.hpp \
		../glm/gtx/associated_min_max.inl \
		../glm/gtx/bit.hpp \
		../glm/gtx/bit.inl \
		../glm/gtx/closest_point.hpp \
		../glm/gtx/closest_point.inl \
		../glm/gtx/color_space.hpp \
		../glm/gtx/color_space_YCoCg.hpp \
		../glm/gtx/color_space_YCoCg.inl \
		../glm/gtx/compatibility.hpp \
		../glm/gtx/compatibility.inl \
		../glm/gtx/component_wise.hpp \
		../glm/gtx/component_wise.inl \
		../glm/gtx/dual_quaternion.hpp \
		../glm/gtx/dual_quaternion.inl \
		../glm/gtx/euler_angles.hpp \
		../glm/gtx/euler_angles.inl \
		../glm/gtx/extend.hpp \
		../glm/gtx/extend.inl \
		../glm/gtx/extended_min_max.hpp \
		../glm/gtx/extended_min_max.inl \
		../glm/gtx/fast_exponential.hpp \
		../glm/gtx/fast_exponential.inl \
		../glm/gtx/fast_square_root.hpp \
		../glm/gtx/fast_square_root.inl \
		../glm/gtx/fast_trigonometry.hpp \
		../glm/gtx/fast_trigonometry.inl \
		../glm/gtx/gradient_paint.hpp \
		../glm/gtx/optimum_pow.hpp \
		../glm/gtx/optimum_pow.inl \
		../glm/gtx/gradient_paint.inl \
		../glm/gtx/handed_coordinate_space.hpp \
		../glm/gtx/handed_coordinate_space.inl \
		../glm/gtx/integer.hpp \
		../glm/gtx/intersect.hpp \
		../glm/gtx/vector_query.hpp \
		../glm/gtx/vector_query.inl \
		../glm/gtx/intersect.inl \
		../glm/gtx/log_base.hpp \
		../glm/gtx/log_base.inl \
		../glm/gtx/matrix_cross_product.hpp \
		../glm/gtx/matrix_cross_product.inl \
		../glm/gtx/matrix_interpolation.hpp \
		../glm/gtx/matrix_interpolation.inl \
		../glm/gtx/matrix_major_storage.hpp \
		../glm/gtx/matrix_major_storage.inl \
		../glm/gtx/matrix_operation.hpp \
		../glm/gtx/matrix_operation.inl \
		../glm/gtx/matrix_query.hpp \
		../glm/gtx/matrix_query.inl \
		../glm/gtx/mixed_product.hpp \
		../glm/gtx/mixed_product.inl \
		../glm/gtx/norm.hpp \
		../glm/gtx/quaternion.hpp \
		../glm/gtx/norm.inl \
		../glm/gtx/normal.hpp \
		../glm/gtx/normal.inl \
		../glm/gtx/normalize_dot.hpp \
		../glm/gtx/normalize_dot.inl \
		../glm/gtx/number_precision.hpp \
		../glm/gtx/number_precision.inl \
		../glm/gtx/orthonormalize.hpp \
		../glm/gtx/orthonormalize.inl \
		../glm/gtx/perpendicular.hpp \
		../glm/gtx/projection.hpp \
		../glm/gtx/projection.inl \
		../glm/gtx/perpendicular.inl \
		../glm/gtx/polar_coordinates.hpp \
		../glm/gtx/polar_coordinates.inl \
		../glm/gtx/raw_data.hpp \
		../glm/gtx/raw_data.inl \
		../glm/gtx/rotate_vector.hpp \
		../glm/gtx/transform.hpp \
		../glm/gtx/transform.inl \
		../glm/gtx/rotate_vector.inl \
		../glm/gtx/spline.hpp \
		../glm/gtx/spline.inl \
		../glm/gtx/std_based_type.hpp \
		../glm/gtx/std_based_type.inl \
		../glm/gtx/string_cast.hpp \
		../glm/gtx/string_cast.inl \
		../glm/gtx/transform2.hpp \
		../glm/gtx/transform2.inl \
		../glm/gtx/vector_angle.hpp \
		../glm/gtx/vector_angle.inl \
		../glm/gtx/wrap.hpp \
		../glm/gtx/wrap.inl \
		../glm/gtx/scalar_multiplication.hpp \
		../glm/gtx/range.hpp \
		include/Shader.h \
		include/TrackballCamera.h \
		include/Camera.h \
		include/Mesh.h \
		include/Buffer.h \
		include/marchingcube.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Scene.o src/Scene.cpp

obj/Buffer.o: src/Buffer.cpp include/Buffer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Buffer.o src/Buffer.cpp

obj/marchingcube.o: src/marchingcube.cpp include/marchingcube.h \
		../glm/glm.hpp \
		../glm/detail/_fixes.hpp \
		../glm/fwd.hpp \
		../glm/detail/type_int.hpp \
		../glm/detail/setup.hpp \
		../glm/simd/platform.h \
		../glm/detail/type_float.hpp \
		../glm/detail/type_vec.hpp \
		../glm/detail/precision.hpp \
		../glm/detail/type_mat.hpp \
		../glm/vec2.hpp \
		../glm/detail/type_vec2.hpp \
		../glm/detail/_swizzle.hpp \
		../glm/detail/_swizzle_func.hpp \
		../glm/detail/type_vec2.inl \
		../glm/vec3.hpp \
		../glm/detail/type_vec3.hpp \
		../glm/detail/type_vec3.inl \
		../glm/vec4.hpp \
		../glm/detail/type_vec4.hpp \
		../glm/detail/type_vec4.inl \
		../glm/detail/type_vec4_simd.inl \
		../glm/mat2x2.hpp \
		../glm/detail/type_mat2x2.hpp \
		../glm/detail/type_mat2x2.inl \
		../glm/detail/func_matrix.hpp \
		../glm/mat2x3.hpp \
		../glm/detail/type_mat2x3.hpp \
		../glm/detail/type_mat2x3.inl \
		../glm/mat2x4.hpp \
		../glm/detail/type_mat2x4.hpp \
		../glm/detail/type_mat2x4.inl \
		../glm/mat3x2.hpp \
		../glm/detail/type_mat3x2.hpp \
		../glm/detail/type_mat3x2.inl \
		../glm/mat3x3.hpp \
		../glm/detail/type_mat3x3.hpp \
		../glm/detail/type_mat3x3.inl \
		../glm/mat3x4.hpp \
		../glm/detail/type_mat3x4.hpp \
		../glm/detail/type_mat3x4.inl \
		../glm/mat4x2.hpp \
		../glm/detail/type_mat4x2.hpp \
		../glm/detail/type_mat4x2.inl \
		../glm/mat4x3.hpp \
		../glm/detail/type_mat4x3.hpp \
		../glm/detail/type_mat4x3.inl \
		../glm/mat4x4.hpp \
		../glm/detail/type_mat4x4.hpp \
		../glm/detail/type_mat4x4.inl \
		../glm/detail/type_mat4x4_simd.inl \
		../glm/detail/func_matrix.inl \
		../glm/geometric.hpp \
		../glm/detail/func_geometric.hpp \
		../glm/detail/func_geometric.inl \
		../glm/detail/func_exponential.hpp \
		../glm/detail/type_vec1.hpp \
		../glm/detail/type_vec1.inl \
		../glm/detail/func_exponential.inl \
		../glm/detail/func_vector_relational.hpp \
		../glm/detail/func_vector_relational.inl \
		../glm/detail/func_vector_relational_simd.inl \
		../glm/detail/_vectorize.hpp \
		../glm/detail/func_exponential_simd.inl \
		../glm/simd/exponential.h \
		../glm/detail/func_common.hpp \
		../glm/detail/func_common.inl \
		../glm/detail/func_common_simd.inl \
		../glm/simd/common.h \
		../glm/detail/func_geometric_simd.inl \
		../glm/simd/geometric.h \
		../glm/detail/func_matrix_simd.inl \
		../glm/simd/matrix.h \
		../glm/trigonometric.hpp \
		../glm/detail/func_trigonometric.hpp \
		../glm/detail/func_trigonometric.inl \
		../glm/detail/func_trigonometric_simd.inl \
		../glm/exponential.hpp \
		../glm/common.hpp \
		../glm/packing.hpp \
		../glm/detail/func_packing.hpp \
		../glm/detail/func_packing.inl \
		../glm/detail/type_half.hpp \
		../glm/detail/type_half.inl \
		../glm/detail/func_packing_simd.inl \
		../glm/matrix.hpp \
		../glm/vector_relational.hpp \
		../glm/integer.hpp \
		../glm/detail/func_integer.hpp \
		../glm/detail/func_integer.inl \
		../glm/detail/func_integer_simd.inl \
		../glm/simd/integer.h \
		include/Mesh.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/marchingcube.o src/marchingcube.cpp

obj/moc_MainWindow.o: moc/moc_MainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_MainWindow.o moc/moc_MainWindow.cpp

obj/moc_GLWindow.o: moc/moc_GLWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_GLWindow.o moc/moc_GLWindow.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

